flags: {}
extra-package-dbs: []
packages:
- '.'
- location: languages/go
  extra-dep: true
- location: languages/php
  extra-dep: true
- location: languages/python
  extra-dep: true
- location: languages/typescript
  extra-dep: true
- location: languages/json
  extra-dep: true
- location: languages/ruby
  extra-dep: true
- location: languages/haskell
  extra-dep: true
resolver: lts-12.17
extra-deps:
  - fused-effects-0.4.0.0
